esphome:
  name: energy-monitor
  platform: ESP32
  board: nodemcu-32s
  includes:
   - powersensor.h
   - EmonLib/EmonLib.h
   - EmonLib/EmonLib.cpp

wifi:
  manual_ip:
    static_ip: 10.10.0.97
    gateway: 10.10.0.1
    subnet: 255.255.254.0
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Energy Monitor Fallback Hotspot"
    password: "FCV8QTAaFy1K"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
      key: !secret home_assistant_encryption

ota:
  password: !secret ota_password


sensor:
- platform: custom
  lambda: |-
    auto my_sensor = new MyPowerSensor();
    App.register_component(my_sensor);
    return {my_sensor->voltage_sensor, my_sensor->current_sensor, my_sensor->realpower_sensor, my_sensor->apparentpower_sensor, my_sensor->powerfactor_sensor};
    
  sensors:
  - name: "Voltage"
  - name: "Current"
  - name: "Real Power"
  - name: "Apparent Power"
  - name: "PowerFactor"